# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 590)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.purchases = QtWidgets.QWidget()
        self.purchases.setObjectName("purchases")
        self.purchases_tabs = QtWidgets.QTabWidget(self.purchases)
        self.purchases_tabs.setGeometry(QtCore.QRect(0, 10, 1051, 521))
        self.purchases_tabs.setObjectName("purchases_tabs")
        self.purchases_list = QtWidgets.QWidget()
        self.purchases_list.setObjectName("purchases_list")
        self.purchases_grid = QtWidgets.QTableView(self.purchases_list)
        self.purchases_grid.setGeometry(QtCore.QRect(8, 13, 1031, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.purchases_grid.setFont(font)
        self.purchases_grid.setObjectName("purchases_grid")
        self.purchases_grid_refresh_button = QtWidgets.QPushButton(self.purchases_list)
        self.purchases_grid_refresh_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.purchases_grid_refresh_button.setObjectName("purchases_grid_refresh_button")
        self.purchases_tabs.addTab(self.purchases_list, "")
        self.putchases_by_name = QtWidgets.QWidget()
        self.putchases_by_name.setObjectName("putchases_by_name")
        self.purchases_grid_name = QtWidgets.QTableView(self.putchases_by_name)
        self.purchases_grid_name.setGeometry(QtCore.QRect(10, 60, 1031, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.purchases_grid_name.setFont(font)
        self.purchases_grid_name.setObjectName("purchases_grid_name")
        self.purchases_by_name_button = QtWidgets.QPushButton(self.putchases_by_name)
        self.purchases_by_name_button.setGeometry(QtCore.QRect(842, 447, 180, 40))
        self.purchases_by_name_button.setObjectName("purchases_by_name_button")
        self.last_name_box = QtWidgets.QComboBox(self.putchases_by_name)
        self.last_name_box.setGeometry(QtCore.QRect(280, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.last_name_box.setFont(font)
        self.last_name_box.setObjectName("last_name_box")
        self.label_10 = QtWidgets.QLabel(self.putchases_by_name)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.purchases_tabs.addTab(self.putchases_by_name, "")
        self.add_purchase = QtWidgets.QWidget()
        self.add_purchase.setObjectName("add_purchase")
        self.customer_box = QtWidgets.QComboBox(self.add_purchase)
        self.customer_box.setGeometry(QtCore.QRect(20, 60, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.customer_box.setFont(font)
        self.customer_box.setObjectName("customer_box")
        self.products_list_grid = QtWidgets.QTableView(self.add_purchase)
        self.products_list_grid.setGeometry(QtCore.QRect(20, 130, 991, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.products_list_grid.setFont(font)
        self.products_list_grid.setObjectName("products_list_grid")
        self.products_indexes = QtWidgets.QLineEdit(self.add_purchase)
        self.products_indexes.setGeometry(QtCore.QRect(392, 61, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.products_indexes.setFont(font)
        self.products_indexes.setObjectName("products_indexes")
        self.stock_box = QtWidgets.QComboBox(self.add_purchase)
        self.stock_box.setGeometry(QtCore.QRect(690, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stock_box.setFont(font)
        self.stock_box.setObjectName("stock_box")
        self.label = QtWidgets.QLabel(self.add_purchase)
        self.label.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.add_purchase)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.add_purchase)
        self.label_3.setGeometry(QtCore.QRect(690, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.add_purchase_button = QtWidgets.QPushButton(self.add_purchase)
        self.add_purchase_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.add_purchase_button.setObjectName("add_purchase_button")
        self.purchases_tabs.addTab(self.add_purchase, "")
        self.del_purchase = QtWidgets.QWidget()
        self.del_purchase.setObjectName("del_purchase")
        self.label_4 = QtWidgets.QLabel(self.del_purchase)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.choose_purchase_box = QtWidgets.QComboBox(self.del_purchase)
        self.choose_purchase_box.setGeometry(QtCore.QRect(20, 70, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_purchase_box.setFont(font)
        self.choose_purchase_box.setObjectName("choose_purchase_box")
        self.del_purchase_button = QtWidgets.QPushButton(self.del_purchase)
        self.del_purchase_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.del_purchase_button.setObjectName("del_purchase_button")
        self.purchases_tabs.addTab(self.del_purchase, "")
        self.tabWidget.addTab(self.purchases, "")
        self.customers = QtWidgets.QWidget()
        self.customers.setObjectName("customers")
        self.customers_tabs = QtWidgets.QTabWidget(self.customers)
        self.customers_tabs.setGeometry(QtCore.QRect(0, 10, 1051, 521))
        self.customers_tabs.setObjectName("customers_tabs")
        self.customers_list = QtWidgets.QWidget()
        self.customers_list.setObjectName("customers_list")
        self.customers_grid = QtWidgets.QTableView(self.customers_list)
        self.customers_grid.setGeometry(QtCore.QRect(8, 13, 1031, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.customers_grid.setFont(font)
        self.customers_grid.setObjectName("customers_grid")
        self.customers_grid_refresh_button = QtWidgets.QPushButton(self.customers_list)
        self.customers_grid_refresh_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.customers_grid_refresh_button.setObjectName("customers_grid_refresh_button")
        self.customers_tabs.addTab(self.customers_list, "")
        self.add_customer = QtWidgets.QWidget()
        self.add_customer.setObjectName("add_customer")
        self.adress_line = QtWidgets.QLineEdit(self.add_customer)
        self.adress_line.setGeometry(QtCore.QRect(290, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adress_line.setFont(font)
        self.adress_line.setObjectName("adress_line")
        self.label_5 = QtWidgets.QLabel(self.add_customer)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.add_customer_button = QtWidgets.QPushButton(self.add_customer)
        self.add_customer_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.add_customer_button.setObjectName("add_customer_button")
        self.label_6 = QtWidgets.QLabel(self.add_customer)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.add_customer)
        self.label_7.setGeometry(QtCore.QRect(298, 9, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.customer_name_line = QtWidgets.QLineEdit(self.add_customer)
        self.customer_name_line.setGeometry(QtCore.QRect(10, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.customer_name_line.setFont(font)
        self.customer_name_line.setObjectName("customer_name_line")
        self.zipcode_line = QtWidgets.QLineEdit(self.add_customer)
        self.zipcode_line.setGeometry(QtCore.QRect(570, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zipcode_line.setFont(font)
        self.zipcode_line.setObjectName("zipcode_line")
        self.label_16 = QtWidgets.QLabel(self.add_customer)
        self.label_16.setGeometry(QtCore.QRect(20, 120, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.passport_line = QtWidgets.QLineEdit(self.add_customer)
        self.passport_line.setGeometry(QtCore.QRect(10, 170, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passport_line.setFont(font)
        self.passport_line.setObjectName("passport_line")
        self.customers_tabs.addTab(self.add_customer, "")
        self.del_customer = QtWidgets.QWidget()
        self.del_customer.setObjectName("del_customer")
        self.label_8 = QtWidgets.QLabel(self.del_customer)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.del_customer_button = QtWidgets.QPushButton(self.del_customer)
        self.del_customer_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.del_customer_button.setObjectName("del_customer_button")
        self.choose_customer_box = QtWidgets.QComboBox(self.del_customer)
        self.choose_customer_box.setGeometry(QtCore.QRect(20, 70, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_customer_box.setFont(font)
        self.choose_customer_box.setObjectName("choose_customer_box")
        self.customers_tabs.addTab(self.del_customer, "")
        self.tabWidget.addTab(self.customers, "")
        self.products = QtWidgets.QWidget()
        self.products.setObjectName("products")
        self.products_tabs = QtWidgets.QTabWidget(self.products)
        self.products_tabs.setGeometry(QtCore.QRect(0, 10, 1051, 521))
        self.products_tabs.setObjectName("products_tabs")
        self.products_list = QtWidgets.QWidget()
        self.products_list.setObjectName("products_list")
        self.product_grid = QtWidgets.QTableView(self.products_list)
        self.product_grid.setGeometry(QtCore.QRect(8, 13, 1031, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_grid.setFont(font)
        self.product_grid.setObjectName("product_grid")
        self.products_grid_refresh_button = QtWidgets.QPushButton(self.products_list)
        self.products_grid_refresh_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.products_grid_refresh_button.setObjectName("products_grid_refresh_button")
        self.products_tabs.addTab(self.products_list, "")
        self.add_product = QtWidgets.QWidget()
        self.add_product.setObjectName("add_product")
        self.product_line_button = QtWidgets.QPushButton(self.add_product)
        self.product_line_button.setGeometry(QtCore.QRect(842, 451, 180, 40))
        self.product_line_button.setObjectName("product_line_button")
        self.label_9 = QtWidgets.QLabel(self.add_product)
        self.label_9.setGeometry(QtCore.QRect(300, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.price_line = QtWidgets.QLineEdit(self.add_product)
        self.price_line.setGeometry(QtCore.QRect(292, 61, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price_line.setFont(font)
        self.price_line.setObjectName("price_line")
        self.product_name_line = QtWidgets.QLineEdit(self.add_product)
        self.product_name_line.setGeometry(QtCore.QRect(12, 61, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.product_name_line.setFont(font)
        self.product_name_line.setObjectName("product_name_line")
        self.label_11 = QtWidgets.QLabel(self.add_product)
        self.label_11.setGeometry(QtCore.QRect(22, 11, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.products_tabs.addTab(self.add_product, "")
        self.del_product = QtWidgets.QWidget()
        self.del_product.setObjectName("del_product")
        self.choose_product_box = QtWidgets.QComboBox(self.del_product)
        self.choose_product_box.setGeometry(QtCore.QRect(20, 70, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_product_box.setFont(font)
        self.choose_product_box.setObjectName("choose_product_box")
        self.del_product_button = QtWidgets.QPushButton(self.del_product)
        self.del_product_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.del_product_button.setObjectName("del_product_button")
        self.label_12 = QtWidgets.QLabel(self.del_product)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.products_tabs.addTab(self.del_product, "")
        self.tabWidget.addTab(self.products, "")
        self.stocks = QtWidgets.QWidget()
        self.stocks.setObjectName("stocks")
        self.stocks_tabs = QtWidgets.QTabWidget(self.stocks)
        self.stocks_tabs.setGeometry(QtCore.QRect(0, 10, 1051, 521))
        self.stocks_tabs.setObjectName("stocks_tabs")
        self.stocks_list = QtWidgets.QWidget()
        self.stocks_list.setObjectName("stocks_list")
        self.stock_grid = QtWidgets.QTableView(self.stocks_list)
        self.stock_grid.setGeometry(QtCore.QRect(10, 10, 1031, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stock_grid.setFont(font)
        self.stock_grid.setObjectName("stock_grid")
        self.stock_grid_refresh_button = QtWidgets.QPushButton(self.stocks_list)
        self.stock_grid_refresh_button.setGeometry(QtCore.QRect(842, 447, 180, 40))
        self.stock_grid_refresh_button.setObjectName("stock_grid_refresh_button")
        self.stocks_tabs.addTab(self.stocks_list, "")
        self.add_stock = QtWidgets.QWidget()
        self.add_stock.setObjectName("add_stock")
        self.stock_name_line = QtWidgets.QLineEdit(self.add_stock)
        self.stock_name_line.setGeometry(QtCore.QRect(12, 61, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stock_name_line.setFont(font)
        self.stock_name_line.setObjectName("stock_name_line")
        self.add_stock_button = QtWidgets.QPushButton(self.add_stock)
        self.add_stock_button.setGeometry(QtCore.QRect(842, 451, 180, 40))
        self.add_stock_button.setObjectName("add_stock_button")
        self.price_reduction_line = QtWidgets.QLineEdit(self.add_stock)
        self.price_reduction_line.setGeometry(QtCore.QRect(292, 61, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price_reduction_line.setFont(font)
        self.price_reduction_line.setObjectName("price_reduction_line")
        self.label_13 = QtWidgets.QLabel(self.add_stock)
        self.label_13.setGeometry(QtCore.QRect(22, 11, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.add_stock)
        self.label_14.setGeometry(QtCore.QRect(300, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stocks_tabs.addTab(self.add_stock, "")
        self.del_stock = QtWidgets.QWidget()
        self.del_stock.setObjectName("del_stock")
        self.label_15 = QtWidgets.QLabel(self.del_stock)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.choose_stock_button = QtWidgets.QComboBox(self.del_stock)
        self.choose_stock_button.setGeometry(QtCore.QRect(20, 70, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_stock_button.setFont(font)
        self.choose_stock_button.setObjectName("choose_stock_button")
        self.del_stock_button = QtWidgets.QPushButton(self.del_stock)
        self.del_stock_button.setGeometry(QtCore.QRect(840, 450, 180, 40))
        self.del_stock_button.setObjectName("del_stock_button")
        self.stocks_tabs.addTab(self.del_stock, "")
        self.tabWidget.addTab(self.stocks, "")
        self.admin = QtWidgets.QWidget()
        self.admin.setObjectName("admin")
        self.admin_line = QtWidgets.QLineEdit(self.admin)
        self.admin_line.setGeometry(QtCore.QRect(10, 60, 1031, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.admin_line.setFont(font)
        self.admin_line.setObjectName("admin_line")
        self.apply_admin_button = QtWidgets.QPushButton(self.admin)
        self.apply_admin_button.setGeometry(QtCore.QRect(840, 480, 191, 41))
        self.apply_admin_button.setObjectName("apply_admin_button")
        self.admin_grid = QtWidgets.QTableView(self.admin)
        self.admin_grid.setGeometry(QtCore.QRect(10, 120, 1031, 341))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.admin_grid.setFont(font)
        self.admin_grid.setObjectName("admin_grid")
        self.tabWidget.addTab(self.admin, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.purchases_tabs.setCurrentIndex(0)
        self.customers_tabs.setCurrentIndex(0)
        self.products_tabs.setCurrentIndex(0)
        self.stocks_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shop"))
        self.purchases_grid_refresh_button.setText(_translate("MainWindow", "Обновить"))
        self.purchases_tabs.setTabText(self.purchases_tabs.indexOf(self.purchases_list), _translate("MainWindow", "Список"))
        self.purchases_by_name_button.setText(_translate("MainWindow", "Найти"))
        self.label_10.setText(_translate("MainWindow", "Фамилия покупателя"))
        self.purchases_tabs.setTabText(self.purchases_tabs.indexOf(self.putchases_by_name), _translate("MainWindow", "Поиск по фамилии"))
        self.label.setText(_translate("MainWindow", "Покупатель"))
        self.label_2.setText(_translate("MainWindow", "Номера товаров"))
        self.label_3.setText(_translate("MainWindow", "Скидка"))
        self.add_purchase_button.setText(_translate("MainWindow", "Добавить"))
        self.purchases_tabs.setTabText(self.purchases_tabs.indexOf(self.add_purchase), _translate("MainWindow", "Добавить"))
        self.label_4.setText(_translate("MainWindow", "Покупка"))
        self.del_purchase_button.setText(_translate("MainWindow", "Удалить"))
        self.purchases_tabs.setTabText(self.purchases_tabs.indexOf(self.del_purchase), _translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.purchases), _translate("MainWindow", "Покупки"))
        self.customers_grid_refresh_button.setText(_translate("MainWindow", "Обновить"))
        self.customers_tabs.setTabText(self.customers_tabs.indexOf(self.customers_list), _translate("MainWindow", "Список"))
        self.label_5.setText(_translate("MainWindow", "ФИО"))
        self.add_customer_button.setText(_translate("MainWindow", "Добавить"))
        self.label_6.setText(_translate("MainWindow", "Индекс"))
        self.label_7.setText(_translate("MainWindow", "Адрес"))
        self.label_16.setText(_translate("MainWindow", "Паспорт"))
        self.customers_tabs.setTabText(self.customers_tabs.indexOf(self.add_customer), _translate("MainWindow", "Добавить"))
        self.label_8.setText(_translate("MainWindow", "Покупатель"))
        self.del_customer_button.setText(_translate("MainWindow", "Удалить"))
        self.customers_tabs.setTabText(self.customers_tabs.indexOf(self.del_customer), _translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customers), _translate("MainWindow", "Покупатели"))
        self.products_grid_refresh_button.setText(_translate("MainWindow", "Обновить"))
        self.products_tabs.setTabText(self.products_tabs.indexOf(self.products_list), _translate("MainWindow", "Список"))
        self.product_line_button.setText(_translate("MainWindow", "Добавить"))
        self.label_9.setText(_translate("MainWindow", "Цена"))
        self.label_11.setText(_translate("MainWindow", "Название"))
        self.products_tabs.setTabText(self.products_tabs.indexOf(self.add_product), _translate("MainWindow", "Добавить"))
        self.del_product_button.setText(_translate("MainWindow", "Удалить"))
        self.label_12.setText(_translate("MainWindow", "Товар"))
        self.products_tabs.setTabText(self.products_tabs.indexOf(self.del_product), _translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.products), _translate("MainWindow", "Товары"))
        self.stock_grid_refresh_button.setText(_translate("MainWindow", "Обновить"))
        self.stocks_tabs.setTabText(self.stocks_tabs.indexOf(self.stocks_list), _translate("MainWindow", "Список"))
        self.add_stock_button.setText(_translate("MainWindow", "Добавить"))
        self.label_13.setText(_translate("MainWindow", "Название"))
        self.label_14.setText(_translate("MainWindow", "Уменьшение цены в %"))
        self.stocks_tabs.setTabText(self.stocks_tabs.indexOf(self.add_stock), _translate("MainWindow", "Добавить"))
        self.label_15.setText(_translate("MainWindow", "Скидка"))
        self.del_stock_button.setText(_translate("MainWindow", "Удалить"))
        self.stocks_tabs.setTabText(self.stocks_tabs.indexOf(self.del_stock), _translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stocks), _translate("MainWindow", "Скидки"))
        self.apply_admin_button.setText(_translate("MainWindow", "Применить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.admin), _translate("MainWindow", "Админ"))

